openapi: 3.1.0
info:
  title: amionInterfcae
  version: '1.0'
  description: Vega Server
servers:
  - url: 'https://qaha-vega-a1.mhqa.local:8443/'
    description: Vega
paths:
  DynamicRoleManager_RestServices-22.1.1.12/dynamicRoleToUserAssignmentServices/service/upload:
    post:
      summary: Uploaded Successfully
      operationId: post-DynamicRoleManager_RestServices-22.1.1.12-dynamicRoleToUserAssignmentServices-service-upload
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  success:
                    type: boolean
                  statusCode:
                    type: number
                  message:
                    type: string
                    minLength: 1
                required:
                  - success
                  - statusCode
                  - message
                x-examples:
                  example-1:
                    success: true
                    statusCode: 204
                    message: 'No shift records were found from amion, So Unassigned all previous shifts assignments'
      description: An Endpoint which is called by Amion Interface for scheduling the shifts by amion
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  source: string
                  wctpChannelURI: string
                  batch: 0
                  shiftRecordsFromAmion:
                    - userName: string
                      shiftStart: string
                      shiftEnd: string
                      uniqueID: string
                      dynamicRoleUniqueID: 0
                      primaryContact: string
                    - userName: string
                      shiftStart: string
                      shiftEnd: string
                      uniqueID: string
                      dynamicRoleUniqueID: 0
                      primaryContact: string
              properties:
                source:
                  type: string
                  minLength: 1
                wctpChannelURI:
                  type: string
                  minLength: 1
                batch:
                  type: number
                shiftRecordsFromAmion:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    type: object
                    properties:
                      userName:
                        type: string
                        minLength: 1
                      shiftStart:
                        type: string
                        minLength: 1
                      shiftEnd:
                        type: string
                        minLength: 1
                      uniqueID:
                        type: string
                        minLength: 1
                      dynamicRoleUniqueID:
                        type: number
                      primaryContact:
                        type: string
                        minLength: 1
                    required:
                      - userName
                      - shiftStart
                      - shiftEnd
                      - uniqueID
                      - dynamicRoleUniqueID
                      - primaryContact
              required:
                - source
                - wctpChannelURI
                - batch
                - shiftRecordsFromAmion
            examples: {}
        description: ''
      security: []
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
